//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан инструментальным средством
//     В случае повторного создания кода изменения, внесенные в этот файл, будут потеряны.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Character
{
	public virtual object Id
	{
		get;
		set;
	}

	public virtual object IsDead
	{
		get;
		set;
	}

	public virtual object Waiting
	{
		get;
		set;
	}

	public virtual object Attribute1
	{
		get;
		set;
	}

}

