//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан инструментальным средством
//     В случае повторного создания кода изменения, внесенные в этот файл, будут потеряны.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Map
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class Cell
	{
		public virtual object X
		{
			get;
			set;
		}

		public virtual object Y
		{
			get;
			set;
		}

		public virtual Character Character
		{
			get;
			set;
		}

	}
}

